DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp

LocalSocket /tmp/clamd.sock
FixStaleSocket yes
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav

LogTime yes
LogClean no
ExtendedDetectionInfo yes

StreamMaxLength 320M
MaxFileSize 320M
MaxScanSize 512M
AlertExceedsMax yes
MaxScanTime 600000

ReadTimeout 300
CommandReadTimeout 10
SendBufTimeout 500
MaxThreads 4
MaxQueue 8
MaxRecursion 16
MaxFiles 2000

ScanArchive yes
ScanPDF yes
ScanOLE2 yes
ConcurrentDatabaseReload no
ExitOnOOM yes
SelfCheck 600
